#!/bin/bash
#make configure
#./configure --enable-double --disable-graphics --disable-cuda

FILES=${HOME}/TCLB/example/tmp/*
for f in $FILES
do
    echo "#############################"
    echo "Processing $f"
    echo "#############################"
    mpirun -np 8 CLB/d2q9_kuper/main $f
done
