#!/bin/bash
#make configure
#./configure --enable-double --disable-graphics --disable-cuda

rm output/*

file_name="karman"
model_name="d2q9"

#make ${model_name}

mpirun -np 8 CLB/${model_name}/main example/${file_name}.xml
#CLB/${model_name}/main example/${file_name}.xml
paraview output/${file_name}_VTK_P00_..pvti &
