AddDensity( name="g0", dx= 0, dy= 0, dz= 0, group="g")
AddDensity( name="g1", dx= 1, dy= 0, dz= 0, group="g")
AddDensity( name="g2", dx=-1, dy= 0, dz= 0, group="g")
AddDensity( name="g3", dx= 0, dy= 1, dz= 0, group="g")
AddDensity( name="g4", dx= 0, dy=-1, dz= 0, group="g")
AddDensity( name="g5", dx= 0, dy= 0, dz= 1, group="g")
AddDensity( name="g6", dx= 0, dy= 0, dz=-1, group="g")
AddDensity( name="g7", dx= 1, dy= 1, dz= 1, group="g")
AddDensity( name="g8", dx=-1, dy= 1, dz= 1, group="g")
AddDensity( name="g9", dx= 1, dy=-1, dz= 1, group="g")
AddDensity( name="g10",dx=-1, dy=-1, dz= 1, group="g")
AddDensity( name="g11",dx= 1, dy= 1, dz=-1, group="g")
AddDensity( name="g12",dx=-1, dy= 1, dz=-1, group="g")
AddDensity( name="g13",dx= 1, dy=-1, dz=-1, group="g")
AddDensity( name="g14",dx=-1, dy=-1, dz=-1, group="g")
AddDensity( name="g15",dx= 1, dy= 1, dz= 0, group="g")
AddDensity( name="g16",dx=-1, dy= 1, dz= 0, group="g")
AddDensity( name="g17",dx= 1, dy=-1, dz= 0, group="g")
AddDensity( name="g18",dx=-1, dy=-1, dz= 0, group="g")
AddDensity( name="g19",dx= 1, dy= 0, dz= 1, group="g")
AddDensity( name="g20",dx=-1, dy= 0, dz= 1, group="g")
AddDensity( name="g21",dx= 1, dy= 0, dz=-1, group="g")
AddDensity( name="g22",dx=-1, dy= 0, dz=-1, group="g")
AddDensity( name="g23",dx= 0, dy= 1, dz= 1, group="g")
AddDensity( name="g24",dx= 0, dy=-1, dz= 1, group="g")
AddDensity( name="g25",dx= 0, dy= 1, dz=-1, group="g")
AddDensity( name="g26",dx= 0, dy=-1, dz=-1, group="g")

#   Phase Field Evolution d3q15:
q_velocities = 15
AddDensity( name="h0", dx= 0, dy= 0, dz= 0, group="h")
AddDensity( name="h1", dx= 1, dy= 0, dz= 0, group="h")
AddDensity( name="h2", dx=-1, dy= 0, dz= 0, group="h")
AddDensity( name="h3", dx= 0, dy= 1, dz= 0, group="h")
AddDensity( name="h4", dx= 0, dy=-1, dz= 0, group="h")
AddDensity( name="h5", dx= 0, dy= 0, dz= 1, group="h")
AddDensity( name="h6", dx= 0, dy= 0, dz=-1, group="h")
AddDensity( name="h7", dx= 1, dy= 1, dz= 1, group="h")
AddDensity( name="h8", dx=-1, dy= 1, dz= 1, group="h")
AddDensity( name="h9", dx= 1, dy=-1, dz= 1, group="h")
AddDensity( name="h10",dx=-1, dy=-1, dz= 1, group="h")
AddDensity( name="h11",dx= 1, dy= 1, dz=-1, group="h")
AddDensity( name="h12",dx=-1, dy= 1, dz=-1, group="h")
AddDensity( name="h13",dx= 1, dy=-1, dz=-1, group="h")
AddDensity( name="h14",dx=-1, dy=-1, dz=-1, group="h")
if (Options$q27){
    q_velocities = 27
    AddDensity( name="h15",dx= 1, dy= 1, dz= 0, group="h")
    AddDensity( name="h16",dx=-1, dy= 1, dz= 0, group="h")
    AddDensity( name="h17",dx= 1, dy=-1, dz= 0, group="h")
    AddDensity( name="h18",dx=-1, dy=-1, dz= 0, group="h")
    AddDensity( name="h19",dx= 1, dy= 0, dz= 1, group="h")
    AddDensity( name="h20",dx=-1, dy= 0, dz= 1, group="h")
    AddDensity( name="h21",dx= 1, dy= 0, dz=-1, group="h")
    AddDensity( name="h22",dx=-1, dy= 0, dz=-1, group="h")
    AddDensity( name="h23",dx= 0, dy= 1, dz= 1, group="h")
    AddDensity( name="h24",dx= 0, dy=-1, dz= 1, group="h")
    AddDensity( name="h25",dx= 0, dy= 1, dz=-1, group="h")
    AddDensity( name="h26",dx= 0, dy=-1, dz=-1, group="h")
}

if (Options$OutFlow){
    AddDensity( name=paste("gold",0:26,sep=""), dx=0,dy=0,dz=0,group="gold")
    AddDensity( name=paste("hold",0:(q_velocities-1),sep=""), dx=0,dy=0,dz=0,group="hold")
}

#   Distribution function for electric potential d3q15:
AddDensity( name="f0", dx= 0, dy= 0, dz= 0, group="f")
AddDensity( name="f1", dx= 1, dy= 0, dz= 0, group="f")
AddDensity( name="f2", dx=-1, dy= 0, dz= 0, group="f")
AddDensity( name="f3", dx= 0, dy= 1, dz= 0, group="f")
AddDensity( name="f4", dx= 0, dy=-1, dz= 0, group="f")
AddDensity( name="f5", dx= 0, dy= 0, dz= 1, group="f")
AddDensity( name="f6", dx= 0, dy= 0, dz=-1, group="f")
AddDensity( name="f7", dx= 1, dy= 1, dz= 1, group="f")
AddDensity( name="f8", dx=-1, dy= 1, dz= 1, group="f")
AddDensity( name="f9", dx= 1, dy=-1, dz= 1, group="f")
AddDensity( name="f10",dx=-1, dy=-1, dz= 1, group="f")
AddDensity( name="f11",dx= 1, dy= 1, dz=-1, group="f")
AddDensity( name="f12",dx=-1, dy= 1, dz=-1, group="f")
AddDensity( name="f13",dx= 1, dy=-1, dz=-1, group="f")
AddDensity( name="f14",dx=-1, dy=-1, dz=-1, group="f")
#   Distribution function for Nearnst PLanck equation d3q15:
AddDensity( name="l0", dx= 0, dy= 0, dz= 0, group="l")
AddDensity( name="l1", dx= 1, dy= 0, dz= 0, group="l")
AddDensity( name="l2", dx=-1, dy= 0, dz= 0, group="l")
AddDensity( name="l3", dx= 0, dy= 1, dz= 0, group="l")
AddDensity( name="l4", dx= 0, dy=-1, dz= 0, group="l")
AddDensity( name="l5", dx= 0, dy= 0, dz= 1, group="l")
AddDensity( name="l6", dx= 0, dy= 0, dz=-1, group="l")
AddDensity( name="l7", dx= 1, dy= 1, dz= 1, group="l")
AddDensity( name="l8", dx=-1, dy= 1, dz= 1, group="l")
AddDensity( name="l9", dx= 1, dy=-1, dz= 1, group="l")
AddDensity( name="l10",dx=-1, dy=-1, dz= 1, group="l")
AddDensity( name="l11",dx= 1, dy= 1, dz=-1, group="l")
AddDensity( name="l12",dx=-1, dy= 1, dz=-1, group="l")
AddDensity( name="l13",dx= 1, dy=-1, dz=-1, group="l")
AddDensity( name="l14",dx=-1, dy=-1, dz=-1, group="l")
