AddField( name="g0" , group="g")
AddField( name="g1" , group="g")
AddField( name="g2" , group="g")
AddField( name="g3" , group="g")
AddField( name="g4" , group="g")
AddField( name="g5" , group="g")
AddField( name="g6" , group="g")
AddField( name="g7" , group="g")
AddField( name="g8" , group="g")
AddField( name="g9" , group="g")
AddField( name="g10", group="g")
AddField( name="g11", group="g")
AddField( name="g12", group="g")
AddField( name="g13", group="g")
AddField( name="g14", group="g")
AddField( name="g15", group="g")
AddField( name="g16", group="g")
AddField( name="g17", group="g")
AddField( name="g18", group="g")
AddField( name="g19", group="g")
AddField( name="g20", group="g")
AddField( name="g21", group="g")
AddField( name="g22", group="g")
AddField( name="g23", group="g")
AddField( name="g24", group="g")
AddField( name="g25", group="g")
AddField( name="g26", group="g")
AddField( name="h0", group="h")
AddField( name="h1", group="h")
AddField( name="h2", group="h")
AddField( name="h3", group="h")
AddField( name="h4", group="h")
AddField( name="h5", group="h")
AddField( name="h6", group="h")
AddField( name="h7", group="h")
AddField( name="h8", group="h")
AddField( name="h9", group="h")
AddField( name="h10",group="h")
AddField( name="h11",group="h")
AddField( name="h12",group="h")
AddField( name="h13",group="h")
AddField( name="h14",group="h")
AddDensity("Temp", dx=0, dy=0, dz=0, group="Thermal")
AddDensity("Cond", dx=0, dy=0, dz=0, group="Thermal")
AddDensity("SurfaceTension", dx=0, dy=0, dz=0, group="Thermal")
AddField("Temp",stencil3d=1, group="Thermal")
AddField("Cond",stencil3d=1, group="Thermal")
AddField("SurfaceTension",stencil3d=1, group="Thermal")

AddQuantity(name="T",unit="K")
AddQuantity(name="ST",unit="N/m")
AddSetting("surfPower", default="1", comment="Use for parabolic representation of surface tension")
AddSetting("sigma_T",           comment="Derivative describing how surface tension changes with temp unit=[N/m2]")
AddSetting("sigma_TT",          comment="Derivative describing how surface tension changes with temp unit=[N/m3]")
AddSetting("T_ref",             comment="Reference temperature at which sigma is set unit=[K]")
AddSetting("T_init",zonal=T,    comment="Initial temperature field unit=[K]")
AddSetting("cp_h",              comment="specific heat for heavy phase unit=[J/kg/K]")
AddSetting("cp_l",              comment="specific heat for light phase unit=[J/kg/K]")
AddSetting("k_h",               comment="thermal conductivity for heavy phase unit=[W/m/K]")
AddSetting("k_l",               comment="thermal conductivity for light phase unit=[W/m/K]")
AddSetting("dT",                comment="Application of vertical temp gradient to speed up initialisation unit=[K]")
AddSetting("dTx", default="0",  comment="Application of horizontal temp gradient to speed up initialisation unit=[K]")
AddSetting("stabiliser", default="1",   comment="If not solving flow field, can adjust temperature timestep")
AddGlobal("TempChange")
if (Options$planarBenchmark){
    AddSetting("T_c", default="10")
    AddSetting("T_h", default="20")
    AddSetting("T_0", default="4")
    AddSetting("myL", default="100")
    AddSetting("MIDPOINT", default="51")
    AddSetting("PLUSMINUS", default="1")
    AddNodeType("BWall",group="ADDITIONALS")
    AddNodeType("TWall",group="ADDITIONALS")
}
AddDensity("RK1", dx=0, dy=0, dz=0, group="Thermal")
AddDensity("RK2", dx=0, dy=0, dz=0, group="Thermal")
AddDensity("RK3", dx=0, dy=0, dz=0, group="Thermal")
AddField("RK1",stencil3d=1, group="Thermal")
AddField("RK2",stencil3d=1, group="Thermal")
AddField("RK3",stencil3d=1, group="Thermal")

AddNodeType("ConstantTemp",group="ADDITIONALS")
AddNodeType("EAdiabatic",group="ADDITIONALS")

