name: 'TCLB Install'
description: 'This action installes TCLB dependencies'
inputs:
  R:
    description: install R
    default: true
  essentials:
    description: install essentials
    default: false
  MPI:
    description: install MPI (openmpi)
    default: 'openmpi'
  python_dev:
    description: install python-dev
    default: false
  rdep:
    description: install python-dev
    default: true
  rinside:
    description: install python-dev
    default: true
runs:
  using: 'composite'
  steps:
    - if: inputs.essentials
      shell: bash
      run: tools/install.sh --sudo essentials
    - if: inputs.R
      shell: bash
      run: tools/install.sh --sudo r
    - if: inputs.rinside
      shell: bash
      run: tools/install.sh --sudo rinside
    - if: inputs.MPI == 'openmpi'
      shell: bash
      run: tools/install.sh --sudo openmpi
    - if: inputs.python_dev
      shell: bash
      run: tools/install.sh --sudo python-dev
    - if: inputs.rdep
      shell: bash
      run: tools/install.sh --sudo rdep
