#!/bin/bash

LIST=$(find -name '*~')
if [ $(echo $LIST | wc -w) -ne 0 ]
then
	rm $LIST 2>/dev/null
fi


LIST=package/src/*
rm $LIST 2>/dev/null

LIST=output/*
rm $LIST 2>/dev/null

LIST=CLB/*
for i in $LIST; do
	if test -d $i; then
		rm -r $i 2>/dev/null
	fi
done

LIST=CLB_*.tar.gz
rm $LIST 2>/dev/null

LIST=Snap_*
rm $LIST 2>/dev/null

LIST='conf.R Dynamics.R'
rm $LIST 2>/dev/null

true