#!/bin/sh
# t2h {$1} html-ize a text file and save as foo.htm
cat > .tmp
FILE=$1
test -z "$FILE" && exit -1
NL="
"
echo "<html>" >$FILE
echo "<body>" >>$FILE
echo "<pre>" >>$FILE
cat .tmp \
| sed -e 's/[[:cntrl:]]/ /g'\
| sed -e 's/http:\/\/[[:graph:]\.\/]*/<A HREF="&">[&]<\/A> /g'\
                                >> $FILE
rm .tmp

echo "</pre>"  >>$FILE
echo "</body>" >>$FILE
echo "</html>" >>$FILE
