#!/bin/bash
#cat > .tmp

FILE=$1
shift
test -z "$FILE" && exit -1
COMMAND=$@

NL="
"

echo "<html>" >$FILE
echo "<body>" >>$FILE
echo "<pre>" >>$FILE
#cat .tmp \
#| sed -e 's/[[:cntrl:]]/ /g'\
#| sed -e 's/http:\/\/[[:graph:]\.\/]*/<A HREF="&">[&]<\/A> /g'\
#                                >> $FILE
#rm .tmp
echo $COMMAND
( $COMMAND 2> >(sed 's/^\(.*\)/<span style="color: red;">\1<\/span>/g') ) >> $FILE
RET=${PIPESTATUS[0]}
echo "</pre>"  >>$FILE
echo "</body>" >>$FILE
echo "</html>" >>$FILE

exit $RET
