name: Testing models

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [d2q9_npe_guo, d2q9_bc, d2q9, d2q9_SRT, d2q9_thin_film, d3q19, d3q19_les, d3q19_heat, d2q9_kuper, d2q9_pf, d2q9_pf_fd, d3q27, d3q27_cumulant, d3q27_cumulant_AVG_IB_SMAG]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ./.github/actions/install
      with:
        r: true
        rdep: true
        openmpi: true
        rinside: true
    - uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-install
    - uses: ./.github/actions/configure
      with:
        gpu: true
        cuda_arch: sm_60
        paranoid: true
    - uses: ./.github/actions/compile
      with:
        model: ${{ matrix.model }}
