name: Testing the test

on: [ push ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: CFD-GO/action_TCLB_test@master
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        install: true
