name: Testing the test

on: [ push ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: CFD-GO/action_TCLB_test@master
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        install: true
